language: objective-c
sudo: false
xcode_workspace: Say.xcworkspace
osx_image: xcode10
xcode_scheme: macOS
install:
  - pod install
matrix:
  include:
    - osx_image: xcode10
      xcode_sdk: macosx
      xcode_scheme: macOS
      xcode_destination: platform=macOS
