//
//  Voice.swift
//  Say
//
//  Created by Seungwon Kim on 2016. 9. 25..
//  Copyright © 2016년 youknowone.org. All rights reserved.
//

import Cocoa

/**
    Voice object for Say.
 
    Voice objects will be automatically generated by `VoiceAPI.voices()`.
    Do not create one yourself.
 */
class VoiceAPI: NSObject {
    let identifier: String
    let comment: String
    let locale: String
    let name: String
    
    override var description: String {
        get {
            return "<Voice: '\(self.name)'(\(self.locale)), '\(self.comment)'>"
        }
    }
    
    /**
        Construct a voice object for Say.
     
        Voice objects will be automatically generated by `VoiceAPI.voices()`.
        Do not create one yourself.
     
        - Parameters:
            - dictionary: the dictionary of voice;
            ** Get from NSSpeechSynthesizer.attributes(forVoice: `voiceIdentifier`)
            ** Do not create one yourself
     */
    init(attributes: [NSSpeechSynthesizer.VoiceAttributeKey : Any]) {
        self.identifier = attributes[NSSpeechSynthesizer.VoiceAttributeKey(rawValue: "VoiceIdentifier")] as! String
        self.comment = attributes[NSSpeechSynthesizer.VoiceAttributeKey(rawValue: "VoiceDemoText")] as! String
        self.locale = attributes[NSSpeechSynthesizer.VoiceAttributeKey(rawValue: "VoiceLocaleIdentifier")] as! String
        self.name = attributes[NSSpeechSynthesizer.VoiceAttributeKey(rawValue: "VoiceName")] as! String
        super.init()
    }

    /**
        List of voices of current system.
     */
    static let voices: [VoiceAPI] = {
        var voices: [VoiceAPI] = []
        for voiceIdentifier in NSSpeechSynthesizer.availableVoices {
            voices.append(VoiceAPI(attributes: NSSpeechSynthesizer.attributes(forVoice: voiceIdentifier)))
        }
        return voices
    }()
}
